config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # Define the books resource and its routes
  resources :books do
    collection do
      post :send_test_email
    end
  end

  # Set the root path to the books#index action
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :datePublished, date_format: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    def index
        @books = Book.all 
        @books = [] if @books.nil?  # Ensure @books is not nil
    end

    def new
        @book = Book.new
       
      end
    
      def create
        @book = Book.new(book_params)
        Rails.logger.debug "Book object before save: #{@book.inspect}"
        if @book.save
          redirect_to books_path, notice: 'Book was successfully created.'
        else
          render :new
        end
      end

      def destroy
        @book = Book.find(params[:id])
        @book.destroy
    
        redirect_to books_path, notice: "Book was successfully deleted."
      end

      def send_test_email
        email = params[:email] # Get the email address from the form
      
        if email.present? && TestMailer.test_email(email).deliver_now
          flash[:success] = "Test email sent successfully!"
        else
          flash[:error] = "Failed to send test email. Please enter a valid email address."
        end
      
        redirect_to books_path
      end
    
      # ...
    
      private
    
      def book_params
        params.require(:book).permit(:title, :author, :description, :datePublished) 
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/email_sender_helper.rb
module EmailSenderHelper
end

app/views/books/_book.html.erb
<div class="govuk-width-container">
  <main class="govuk-main-wrapper">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">
          <%= book.title %>
          <span class="govuk-caption-l"><%= book.author %></span>
        </h1>
        <div class="govuk-inset-text">
          <%= book.description %>
        </div>
      </div>
      <div class="govuk-grid-column-one-third">
        <h2 class="govuk-heading-s"><%= book.datePublished.strftime("%d %b %y") %></h2>
        <%= button_to "delete", { controller: :books, action: 'destroy', id: book.id }, method: :delete, class: "govuk-button govuk-button--warning" %>
      </div>
    </div>
  </main>
</div>
<hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">

app/views/books/_email_form.html.erb
<%= form_with(url: send_test_email_books_path, method: :post, id: "email-form", style: "display: none;") do |form| %>
    <div class="govuk-form-group">
      <%= form.label :email, class: "govuk-label" %>
      <%= form.text_field :email, class: "govuk-input" %>
    </div>
    <%= form.submit "Send Test Email", class: "govuk-button govuk-button--secondary" %>
  
    <!-- Add a cancel button -->
    <%= button_tag "Cancel", type: "button", id: "cancel-email-form", class: "govuk-button govuk-button--warning" %>
  <% end %>

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->
<%= link_to "Add New Book", new_book_path, class: "govuk-button" %>
<!-- Add an ID to the Send Test Email link -->
<%= link_to "Test Email", "#", id: "show-email-form", class: "govuk-button govuk-button--secondary" %>

<!-- Render the email form partial -->
<%= render 'email_form' %>
<!-- Render the book view partial -->
<%= render partial: 'book', collection: @books %>

<!-- jQuery script -->
<script>
   $(document).ready(function() {
     $("#email-form").hide();
     $("#show-email-form").click(function() {
       $("#email-form").show();
     });
   
     $("#cancel-email-form").click(function() {
       $("#email-form").hide();
     });
   });
</script>

app/views/books/new.html.erb
<%= form_with(model: @book, url: books_path, method: :post) do |form| %>
  <div class="govuk-form-group">
    <h1 class="govuk-label-wrapper">
      <label class="govuk-label govuk-label--l" for="book-title">
        Please Add A New Book Here
      </label>
    </h1>
  </div>

  <div class="govuk-form-group">
    <label class="govuk-label govuk-label--m" for="book-title">
      Title
    </label>
    <%= form.text_field :title, class: "govuk-input", id: "book-title" %>
  </div>

  <div class="govuk-form-group">
    <label class="govuk-label govuk-label--m" for="book-author">
      Author
    </label>
    <%= form.text_field :author, class: "govuk-input", id: "book-author" %>
  </div>

  <div class="govuk-form-group">
    <label class="govuk-label govuk-label--m" for="book-description">
      Description
    </label>
    <%= form.text_area :description, class: "govuk-textarea", id: "book-description" %>
  </div>

  <div class="govuk-form-group">
    <label class="govuk-label govuk-label--m" for="book-datePublished">
      Date Published
    </label>
    <%= form.date_field :datePublished, class: "govuk-input", id: "book-datePublished" %>
    <% if @book.errors[:datePublished].any? %>
  <span id="datePublished-error" class="govuk-error-message">
    <span class="govuk-visually-hidden">Error:</span> <%= @book.errors[:datePublished].first %>
  </span>
<% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Book', class: "govuk-button govuk-button--start" %>
    <%= link_to 'Back', books_path, class: "govuk-button govuk-button--start" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="govuk-template ">

<head>
  <meta charset="utf-8">
  <title>GOV.UK - The best place to find government services and information</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#0b0c0c">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
  <link rel="mask-icon" href="https://design-system.service.gov.uk/assets/images/govuk-mask-icon.svg" color="#0b0c0c">
  <link rel="apple-touch-icon" sizes="180x180" href="https://design-system.service.gov.uk/assets/images/govuk-apple-touch-icon-180x180.png">
  <link rel="apple-touch-icon" sizes="167x167" href="https://design-system.service.gov.uk/assets/images/govuk-apple-touch-icon-167x167.png">
  <link rel="apple-touch-icon" sizes="152x152" href="https://design-system.service.gov.uk/assets/images/govuk-apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" href="https://design-system.service.gov.uk/assets/images/govuk-apple-touch-icon.png">
  <link href="https://design-system.service.gov.uk/stylesheets/main-8b722cf33a433600f925958f167685f3.css" rel="stylesheet">
  <link href="https://design-system.service.gov.uk/styles/layout/grid-annotate-14e3effc6e1723169575be440d0c76c5.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 
</head>

  <body class="govuk-template__body">
    <script>
      document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');
    </script>
      <header class="govuk-header " role="banner" data-module="govuk-header">
    <div class="govuk-header__container govuk-width-container">
      <div class="govuk-header__logo">
        <a href="/" class="govuk-header__link govuk-header__link--homepage">
          <span class="govuk-header__logotype">
            <!--[if gt IE 8]><!-->
            <svg
              aria-hidden="true"
              focusable="false"
              class="govuk-header__logotype-crown"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 132 97"
              height="30"
              width="36">
              <path
                fill="currentColor" fill-rule="evenodd"
                d="M25 30.2c3.5 1.5 7.7-.2 9.1-3.7 1.5-3.6-.2-7.8-3.9-9.2-3.6-1.4-7.6.3-9.1 3.9-1.4 3.5.3 7.5 3.9 9zM9 39.5c3.6 1.5 7.8-.2 9.2-3.7 1.5-3.6-.2-7.8-3.9-9.1-3.6-1.5-7.6.2-9.1 3.8-1.4 3.5.3 7.5 3.8 9zM4.4 57.2c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.5-1.5-7.6.3-9.1 3.8-1.4 3.5.3 7.6 3.9 9.1zm38.3-21.4c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.6-1.5-7.6.3-9.1 3.8-1.3 3.6.4 7.7 3.9 9.1zm64.4-5.6c-3.6 1.5-7.8-.2-9.1-3.7-1.5-3.6.2-7.8 3.8-9.2 3.6-1.4 7.7.3 9.2 3.9 1.3 3.5-.4 7.5-3.9 9zm15.9 9.3c-3.6 1.5-7.7-.2-9.1-3.7-1.5-3.6.2-7.8 3.7-9.1 3.6-1.5 7.7.2 9.2 3.8 1.5 3.5-.3 7.5-3.8 9zm4.7 17.7c-3.6 1.5-7.8-.2-9.2-3.8-1.5-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.3 3.5-.4 7.6-3.9 9.1zM89.3 35.8c-3.6 1.5-7.8-.2-9.2-3.8-1.4-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.4 3.6-.3 7.7-3.9 9.1zM69.7 17.7l8.9 4.7V9.3l-8.9 2.8c-.2-.3-.5-.6-.9-.9L72.4 0H59.6l3.5 11.2c-.3.3-.6.5-.9.9l-8.8-2.8v13.1l8.8-4.7c.3.3.6.7.9.9l-5 15.4v.1c-.2.8-.4 1.6-.4 2.4 0 4.1 3.1 7.5 7 8.1h.2c.3 0 .7.1 1 .1.4 0 .7 0 1-.1h.2c4-.6 7.1-4.1 7.1-8.1 0-.8-.1-1.7-.4-2.4V34l-5.1-15.4c.4-.2.7-.6 1-.9zM66 92.8c16.9 0 32.8 1.1 47.1 3.2 4-16.9 8.9-26.7 14-33.5l-9.6-3.4c1 4.9 1.1 7.2 0 10.2-1.5-1.4-3-4.3-4.2-8.7L108.6 76c2.8-2 5-3.2 7.5-3.3-4.4 9.4-10 11.9-13.6 11.2-4.3-.8-6.3-4.6-5.6-7.9 1-4.7 5.7-5.9 8-.5 4.3-8.7-3-11.4-7.6-8.8 7.1-7.2 7.9-13.5 2.1-21.1-8 6.1-8.1 12.3-4.5 20.8-4.7-5.4-12.1-2.5-9.5 6.2 3.4-5.2 7.9-2 7.2 3.1-.6 4.3-6.4 7.8-13.5 7.2-10.3-.9-10.9-8-11.2-13.8 2.5-.5 7.1 1.8 11 7.3L80.2 60c-4.1 4.4-8 5.3-12.3 5.4 1.4-4.4 8-11.6 8-11.6H55.5s6.4 7.2 7.9 11.6c-4.2-.1-8-1-12.3-5.4l1.4 16.4c3.9-5.5 8.5-7.7 10.9-7.3-.3 5.8-.9 12.8-11.1 13.8-7.2.6-12.9-2.9-13.5-7.2-.7-5 3.8-8.3 7.1-3.1 2.7-8.7-4.6-11.6-9.4-6.2 3.7-8.5 3.6-14.7-4.6-20.8-5.8 7.6-5 13.9 2.2 21.1-4.7-2.6-11.9.1-7.7 8.8 2.3-5.5 7.1-4.2 8.1.5.7 3.3-1.3 7.1-5.7 7.9-3.5.7-9-1.8-13.5-11.2 2.5.1 4.7 1.3 7.5 3.3l-4.7-15.4c-1.2 4.4-2.7 7.2-4.3 8.7-1.1-3-.9-5.3 0-10.2l-9.5 3.4c5 6.9 9.9 16.7 14 33.5 14.8-2.1 30.8-3.2 47.7-3.2z"></path>
            </svg>
            <!--<![endif]-->
            <!--[if IE 8]>
          <img src="/assets/images/govuk-logotype-crown.png" class="govuk-header__logotype-crown-fallback-image" width="36" height="32" alt="">
          <![endif]-->
            <span class="govuk-header__logotype-text">
              GOV.UK
            </span>
          </span>
        </a>
      </div>
    </div>
  </header>

    <div class="govuk-width-container">
      <main class="govuk-main-wrapper" id="main-content" role="main">
      <%= yield %>
      </main>
    </div>

    <footer class="govuk-footer " role="contentinfo">
    <div class="govuk-width-container ">
      <div class="govuk-footer__meta">
        <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
          <svg
            aria-hidden="true"
            focusable="false"
            class="govuk-footer__licence-logo"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 483.2 195.7"
            height="17"
            width="41">
            <path
              fill="currentColor"
              d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145" />
          </svg>
          <span class="govuk-footer__licence-description">
            All content is available under the
            <a
              class="govuk-footer__link"
              href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
              rel="license">Open Government Licence v3.0</a>, except where otherwise stated
          </span>
        </div>
        <div class="govuk-footer__meta-item">
          <a
            class="govuk-footer__link govuk-footer__copyright-logo"
            href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>
        </div>
      </div>
    </div>
  </footer>
  <script src="/govuk-frontend/all.js"></script>
  <script>
    window.GOVUKFrontend.initAll()
  </script>
  </body>
</html>